version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=plateform_db
      - DOCKER_HOST=unix:///var/run/docker.sock  # Enable Docker in Docker
      - DIGITALOCEAN_ACCESS_TOKEN=${DIGITALOCEAN_ACCESS_TOKEN}  # Secure API key
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for DinD
      - ~/.docker/machine:/root/.docker/machine  # Mount Docker Machine SSH keys
      - ~/.ssh:/root/.ssh  # Mount SSH keys

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
